AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description:  > 
  CloudFormation APC_HEAD template 

Parameters:
  EnvName:
    Description: "Your environment name here"
    Type: String
    Default: defalt
  CloudWatchAlarmEmail:
    Description: "The e-mail to notify errors"
    Type: String
    Default: ""

Resources:
  StreamDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "test_HEAD-deploy-bucket-${EnvName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true


  APCHEADKinesisFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn: StreamDataBucket
    Properties:
      DeliveryStreamName: test_APC_HEAD
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub "arn:aws:s3:::test_HEAD-deploy-bucket-${EnvName}"
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 64
        ErrorOutputPrefix: error/
        Prefix: "uuid/!{partitionKeyFromQuery:uuid}/!{timestamp:'year='yyyy'/month='MM'/day='dd'/hour='HH}/"
        RoleARN: !Sub "${FirehoseRole.Arn}"
        DynamicPartitioningConfiguration:
          Enabled: true
          # RetryOptions:
          #   DurationInSeconds: 60
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: /aws/kinesisfirehose/test_APC_HEAD
          LogStreamName: S3Delivery       
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: MetadataExtraction
              Parameters:
                - ParameterName: MetadataExtractionQuery
                  ParameterValue: '{uuid: .uuid}'
                - ParameterName: JsonParsingEngine
                  ParameterValue: JQ-1.6
  
  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: KinesisFirehoseRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole

    

# ------------------------------------------------------------#
# Kinesis Data Firehose Error LogGroup (CloudWatch Logs)
# ------------------------------------------------------------#

  LogGroupFirehoseActivityLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/kinesisfirehose/test_APC_HEAD
      RetentionInDays: 365




