name: deploy-pkg-template ##関数毎変更箇所

on:
  push:
    branches:
      - develop
      - staging
      - feature-*
      - production

#-------------------------#
# 環境変数
#-------------------------#

jobs:
  deploy_S3:
    name: Create Deploy Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Create DeployBucket
        uses: ./.github/actions/create-deployBucket

      # - name: Copy Swagger to S3
      #   run: aws s3 cp ./swagger.yml s3://pkg-deploy-bucket-${GITHUB_REF#refs/heads/}

  
  sam-deploy:
    needs: deploy_S3
    runs-on: ubuntu-18.04

    steps:
      - name: checkoout
        uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@v2

      - name: sam setup
        uses: aws-actions/setup-sam@v1

      #AWS環境への認証
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # sam build
      - name: sam build
        uses: ./.github/actions/sam-build

      # sam deploy
      - name: sam deploy
        uses: ./.github/actions/sam-deploy
